[package]
name = "mapforge-player"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
eframe.workspace = true
egui.workspace = true
mapforge-core = { path = "../../crates/mapforge-core" }
serde_json.workspace = true
uuid.workspace = true
